<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Backnone Test</title>

    <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap-theme.css">
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>

<button id="btnGetUsers" class="btn btn-primary">Get users</button>
<button class="btn btn-primary">Get a single user</button>

<ul id="userList"></ul>

<script src="/vendor/jquery/dist/jquery.js"></script>
<script src="/vendor/underscore/underscore.js"></script>
<script src="/vendor/bootstrap/dist/js/bootstrap.js"></script>
<script src="/vendor/backbone/backbone.js"></script>
<script src="/js/main.js"></script>
</body>
</html>