<?php include_once 'head.phtml' ?>
<body>

<entity-list></entity-list>

<new-entity-modal></new-entity-modal>
<view-update-modal></view-update-modal>

<!-- Libs -->
<script src="/vendor/jquery/dist/jquery.min.js"></script>
<script src="/vendor/underscore/underscore.js"></script>
<script src="/vendor/bootstrap/dist/js/bootstrap.js"></script>
<script src="/vendor/backbone/backbone.js"></script>
<script src="/vendor/riot/riot.min.js"></script>

<!-- Tags -->
<script src="/js/components/entity-list.js"></script>
<script src="/js/components/new-entity-modal.js"></script>
<script src="/js/components/view-update-modal.js"></script>
<script src="/js/components/alert.js"></script>

<!-- Ours -->
<script src="/js/common.js"></script>
<script src="/js/crud.js"></script>
</body>
</html>