<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SCT Generic Backend</title>

    <meta name="base_url" content="<?= \Settings\AppSettings::$base_url; ?>"/>

    <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap-theme.css">
    <link rel="stylesheet" href="/css/styles.css">
</head>