<?php include_once 'head.phtml' ?>
<body>

<collection-list></collection-list>

<!-- Libs -->
<script src="/vendor/jquery/dist/jquery.min.js"></script>
<script src="/vendor/underscore/underscore.js"></script>
<script src="/vendor/bootstrap/dist/js/bootstrap.js"></script>
<script src="/vendor/backbone/backbone.js"></script>
<script src="/vendor/riot/riot.min.js"></script>

<!-- Tags -->
<script src="/js/components/collection-list.js"></script>
<script src="/js/components/alert.js"></script>

<!-- Our js -->
<script src="/js/common.js"></script>
<script src="/js/home.js"></script>ire
</body>
</html>