<script src="https://code.jquery.com/jquery-1.10.2.js" ></script >

<script >
    $(document).ready(function () {

        $("#submit").on('click', function () {
            $.get(
                '/users?where=' + encodeURIComponent($('#query').val()),
                function(response)
                {
                    $('#response').html(JSON.stringify(response));
                }
            );

            return false;
        });
    });


</script >

<form name="form1" id="form1" >
    <textarea name="query" id="query" cols="50" rows="10" >
{
  "name": { "$regex" : "/^raf.*/"}

}
    </textarea >

    <input type="button" name="submit" value="submit" id="submit" >
</form >

<div id="response"></div>